SET(CMAKE_QUOTE_INCLUDE_PATHS ON)

SET(CMAKE_STATIC_LIBRARY_PREFIX "")
SET(CMAKE_STATIC_LIBRARY_SUFFIX ".lib")
SET(CMAKE_SHARED_LIBRARY_PREFIX "")
SET(CMAKE_SHARED_LIBRARY_SUFFIX ".dll")
SET(CMAKE_IMPORT_LIBRARY_PREFIX "")
SET(CMAKE_IMPORT_LIBRARY_SUFFIX ".lib")
SET(CMAKE_EXECUTABLE_SUFFIX ".exe")
SET(CMAKE_LINK_LIBRARY_SUFFIX ".lib")
SET(CMAKE_DL_LIBS "")

SET(CMAKE_FIND_LIBRARY_PREFIXES "")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib")

SET(CMAKE_C_LINK_EXECUTABLE "${SYMBIAN_LD} <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET>")
SET(CMAKE_CXX_LINK_EXECUTABLE "${SYMBIAN_LD} <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET>")

SET(EPOCLIB "${SYMBIAN_EPOCROOT}\\EPOC32\\RELEASE\\ARMV5\\LIB")

SET(CRT_LIBS "${SYMBIAN_RUNTIME_LIBS_LIST}")
SEPARATE_ARGUMENTS(CRT_LIBS)
FOREACH(CRT_LIB ${CRT_LIBS})
    SET(EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS} \"${EPOCLIB}\\${CRT_LIB}\"")
ENDFOREACH(CRT_LIB)

IF (SYMBIAN_TOOLCHAIN STREQUAL "GCCE")
    EXECUTE_PROCESS(COMMAND "${CMAKE_GENERATOR_CXX}" -print-libgcc-file-name
                    OUTPUT_VARIABLE LIBGCC_PATH)
    GET_FILENAME_COMPONENT(STD_LIB_PATH "${LIBGCC_PATH}" PATH)
ELSE (SYMBIAN_TOOLCHAIN STREQUAL "GCCE")
    MESSAGE(FATAL_ERROR "Unsupported symbian toolchain")
ENDIF (SYMBIAN_TOOLCHAIN STREQUAL "GCCE")

SET(EPOCINC_WIN "${SYMBIAN_EPOCROOT}\\EPOC32\\INCLUDE")
FILE(TO_CMAKE_PATH "${EPOCINC_WIN}" EPOCINC)
SET(CXX_FLAGS "${CXX_FLAGS} ${SYMBIAN_INCLUDE_OPTION} ${EPOCINC}")

SET(EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS} ${SYMBIAN_STATIC_LIBS_PATH} \"${STD_LIB_PATH}\" ${SYMBIAN_STATIC_LIBS_LIST}")
SET(EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS} ${SYMBIAN_LINKER_ENTRY_OPTION} _E32Startup")
SET(EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS} ${SYMBIAN_CODE_SEGMENT_START} 0x8000 ${SYMBIAN_DATA_SEGMENT_START} 0x400000")
SET(EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS} ${SYMBIAN_SYMVER_OPTION}")
SET(CMAKE_EXE_LINKER_FLAGS "${EXE_LINKER_FLAGS}" CACHE STRING "")

SET(CMAKE_EXE_LINKER_FLAGS_DEBUG "${SYMBIAN_UDEB_LINK_FLAGS}" CACHE STRING "")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE "${SYMBIAN_UREL_LINK_FLAGS}" CACHE STRING "")
SET(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_DEBUG}" CACHE STRING "")
SET(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "${CMAKE_EXE_LINKER_FLAGS_RELEASE}" CACHE STRING "")

SET (CMAKE_SHARED_LIBRARY_C_FLAGS "${SYMBIAN_SHARED_OBJECT_OPTION}")
SET (CMAKE_SHARED_LIBRARY_CXX_FLAGS "${SYMBIAN_SHARED_OBJECT_OPTION}")

SET(CCDEFS "${CCDEFS} ${SYMBIAN_COMPILER_DEFINES}  -D__SYMBIAN32__ -D__SERIES60_31__ -D__SERIES60_3X__ -D__EPOC32__")
SET(CCDEFS "${CCDEFS} -D__MARM__ -D__EABI__ -D__MARM_ARMV5__ -D__EXE__ -D__SUPPORT_CPP_EXCEPTIONS__ ")
SET(CCDEFS "${CCDEFS} ${SYMBIAN_PLATFORM_DEFINES}")

SET(CMAKE_C_FLAGS "${SYMBIAN_C_LANG_OPTION} ${SYMBIAN_PREINCLUDE_OPTION} ${SYMBIAN_CCFLAGS} ${CXX_FLAGS} ${CCDEFS}" CACHE STRING "")
SET(CMAKE_CXX_FLAGS "${SYMBIAN_CPP_LANG_OPTION} ${SYMBIAN_PREINCLUDE_OPTION} ${SYMBIAN_CCFLAGS} ${CXX_FLAGS} ${CCDEFS}" CACHE STRING "")
